# This file was generated by GoReleaser. DO NOT EDIT.
cask "watson-tui" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e1b44ea036ec87912d0437dbf6498cc81954c04deb29795109960062126c5306"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b9281e88ab958bbd7b615f9a779fafd31a7829f79e00bced7958630c3fccadf"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fdd7dbd521e06bb5eab51e0e53807b6ff57d1dccb62f6b26ada924814784e86b"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f26d71b0190eb3091ef816d0e539e86b243a8d8952bd44836d266efbac18d2a2"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "watson-tui"
  desc "Schlanke Terminal-UI für Watson-Zeiterfassung"
  homepage "https://github.com/schnaq/watson-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watson-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watson-tui"]
    end
  end

  # No zap stanza required

end
