# This file was generated by GoReleaser. DO NOT EDIT.
cask "watson-tui" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5a5b7fdf795013e68d3a0f22cc3a1b88f7b9fae2d4043380228d64b9ed3266d8"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a852ecf44b60902d88437d51efe8090cf09d098d28b42195eeedacf571a76a87"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "235be3ca6b0d7987f9b1ddd27dd53c2bc9f8152d2103bc9dd86df048effdb913"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ccb10166c601f76560fb0671947b712a8d8861fb96b3acea5b238f984c404e29"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "watson-tui"
  desc "Schlanke Terminal-UI für Watson-Zeiterfassung"
  homepage "https://github.com/schnaq/watson-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watson-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watson-tui"]
    end
  end

  # No zap stanza required

end
