# This file was generated by GoReleaser. DO NOT EDIT.
cask "watson-tui" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "1fccf52a2367e09197b3d02e530702235d9890a5de8336ca6ef16020612e664f"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3022c29e46a7ec8d9381042b2014942185ca72c1e7a7dcca17baf043b987fd5c"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dccd1cebed72a7d68f4fd7d8f4423319c3f541f30cf2947b53a91b3e67819431"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb227405bcfdb7b836bbba9706134bc2bfbf803cacf1698c0b7f763eb75d3010"
      url "https://github.com/schnaq/watson-tui/releases/download/v#{version}/watson-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "watson-tui"
  desc "Schlanke Terminal-UI für Watson-Zeiterfassung"
  homepage "https://github.com/schnaq/watson-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "watson-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/watson-tui"]
    end
  end

  # No zap stanza required

end
